# Generated by Django 4.1.3 on 2022-11-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
            ],
        ),
    ]
